################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[cn]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/cn"
weight = 2
